// ==================== CONFIGURACIÓN ====================
// Cambia únicamente estos campos: nombre, apodo, password, mensaje,
// flores, colores, cantidadFlores, frase y velocidad.
const personas=[
 {nombre:'nicole',apodo:'niki',password:'cartuchera',mensaje:'feliz dia del amor y la amistad mi buena amiga niki que quiero mucho.',flores:['rosa','rosa','margarita'],colores:['#c74667','#e98da4','#f5b5c4'],cantidadFlores:5,frase:'Un ramo empieza a tomar forma, lentamente...',velocidad:1},
 {nombre:'alexandra',apodo:'alexa',password:'tranquilidad',mensaje:'feliz dia alexa muchas gracias por tu amistad y por todas las risas te aprecio demasiado.',flores:['tulipan','tulipan','margarita'],colores:['#e36582','#f4a2b2','#ffc7ce'],cantidadFlores:5,frase:'Un ramo de tulipanes despierta para ti...',velocidad:1},
 {nombre:'felipe',apodo:'saenz',password:'manilla',mensaje:'feliz dia mi estimado muchas gracias por todas la risas y las charlas espero esta amistad continue.',flores:['girasol','girasol','margarita'],colores:['#efad28','#f8ca54','#e68629'],cantidadFlores:5,frase:'Un poco de sol comienza a reunirse...',velocidad:1},
 {nombre:'danna',apodo:'adoptada',password:'prom2028',mensaje:'auqnue nos conocimos hace muy poco pasaron cosas muy divertidas feliz dia espero la pases super .',flores:['margarita','margarita','lavanda'],colores:['#fff8e9','#ffffff','#edc557'],cantidadFlores:5,frase:'Un ramo ligero se prepara para ti...',velocidad:1},
 {nombre:'aleza',apodo:'aleza',password:'regalo',mensaje:'feliz dia la he pasado super, ere una muy buena amiga y me gustaria decirte una ultima cosa nose si un dia podriamos ser algo mas que amigos no qtienes que responder si no quieres.',flores:['cerezo','cerezo','cerezo'],colores:['#f2a3bc','#ffd0df','#df7596'],cantidadFlores:5,frase:'Unas ramas de cerezo empiezan a florecer...',velocidad:1},
 {nombre:'oscar',apodo:'oca',password:'manoseador',mensaje:'mi estimado feliz dia espero que vengas años con mas risas y muchas mas improvisadas.',flores:['lavanda','lavanda','margarita'],colores:['#9172bd','#bca5dc','#765b98'],cantidadFlores:5,frase:'La lavanda se abre con calma...',velocidad:1},
 {nombre:'gamboa',apodo:'gamba',password:'ojialegre',mensaje:'mi estimado feliz dia este año fue de muchas  risas y diversion y espero continue haci .',flores:['loto','loto','margarita'],colores:['#e9a6c9','#f7cde0','#fff0db'],cantidadFlores:5,frase:'Un ramo de lotos encuentra su luz...',velocidad:1},
 {nombre:'angel',apodo:'arias',password:'hades',mensaje:'muchahco espero esta amistad continue por mucho tiempo feliz dia .',flores:['hibisco','hibisco','margarita'],colores:['#d94d71','#f37b98','#f7a9b8'],cantidadFlores:5,frase:'Un hibisco abre su color para ti...',velocidad:1},
 {nombre:'miguel',apodo:'marihuano',password:'ñajarra',mensaje:'ñajarra feliz dia ojala esta amistad se eterna mi grana amigo ñajarra .',flores:['dalia','dalia','lavanda'],colores:['#bd75ae','#dfa5d4','#f2c7e5'],cantidadFlores:5,frase:'Las dalias comienzan a reunirse...',velocidad:1},
 {nombre:'malfitano',apodo:'enano',password:'enano',mensaje:'epa el enano 5 años de amistad que aun perduran como no lo se pero espero siga haci feliz dia .',flores:['especial','rosa','lavanda'],colores:['#d7a95c','#efd78d','#f8eabc'],cantidadFlores:5,frase:'Un ramo único estaba esperando por ti...',velocidad:1}
];
const $=x=>document.getElementById(x);let actual,sketch,timer;function show(x){['welcome','garden','letter'].forEach(s=>$(s).classList.toggle('active',s===x));}
function ramo(persona){if(sketch)sketch.remove();$('flower-stage').innerHTML='';$('flower-reveal').classList.remove('show');sketch=new p5(p=>{let t=0,W,H,kind,colors;const styles={rosa:['rose',['#c74667','#e98da4','#f5b5c4']],tulipanes:['tulip',['#e36582','#f4a2b2','#ffc7ce']],girasoles:['sun',['#efad28','#f8ca54','#e68629']],margaritas:['daisy',['#fff8e9','#ffffff','#edc557']],cerezo:['cherry',['#f2a3bc','#ffd0df','#df7596']],lavanda:['lavender',['#9172bd','#bca5dc','#765b98']],loto:['lotus',['#e9a6c9','#f7cde0','#fff0db']],hibisco:['hibiscus',['#d94d71','#f37b98','#f7a9b8']],dalias:['dahlia',['#bd75ae','#dfa5d4','#f2c7e5']],especial:['special',['#d7a95c','#efd78d','#f8eabc']]};const stems=[[-.38,.12],[-.19,-.04],[0,-.18],[.2,-.05],[.39,.13]];let reveal=false;const E=v=>v<.5?2*v*v:1-Math.pow(-2*v+2,2)/2,at=(a,d)=>Math.max(0,Math.min(1,(t-a)/d));
    p.setup=()=>{let r=$('flower-stage').getBoundingClientRect();W=Math.max(280,r.width);H=Math.max(390,r.height);p.createCanvas(W,H).parent('flower-stage');p.angleMode(p.DEGREES);kind=styles[persona.flores[0]]?.[0]||'special';colors=persona.colores;};
function stem(i,q){let[l,up]=stems[i],x=W/2+l*W*.38,y=H*(.31+up*.2);p.noFill();p.stroke('#4f8864');p.strokeWeight(i===2?7:5);p.beginShape();for(let n=0;n<48*q;n++){let z=n/48;p.vertex(p.bezierPoint(W/2,x+l*24,x-l*10,x,z),p.bezierPoint(H*.91,H*.68,H*.48,y,z));}p.endShape();return[x,y];}
function leaf(x,y,a,s,q){if(!q)return;p.push();p.translate(x,y);p.rotate(a);p.scale(E(q));p.noStroke();p.fill('#5d9970');p.beginShape();p.vertex(0,0);p.bezierVertex(-s,-s,-s*1.5,s*.2,-s*1.8,0);p.bezierVertex(-s,s*.7,-s*.2,s*.3,0,0);p.endShape();p.stroke('#c2dcae');p.strokeWeight(1);p.line(0,0,-s*1.4,0);p.pop();}
function petal(a,r,len,w,c,q){p.push();p.rotate(a);p.translate(0,-r);p.rotate((q-1)*24);p.noStroke();p.fill(c);p.beginShape();p.vertex(0,0);p.bezierVertex(-w,-len*.25,-w*.8,-len,0,-len);p.bezierVertex(w*.8,-len,w,-len*.25,0,0);p.endShape();p.fill(255,255,255,18);p.ellipse(0,-len*.58,w*.5,len*.55);p.pop();}
function bloom(x,y,i,q){if(!q)return;q=E(q);p.push();p.translate(x,y);p.scale(.7+q*.3);if(kind==='tulip'){p.noStroke();p.fill(colors[0]);p.beginShape();p.vertex(-30,14);p.bezierVertex(-37,-30,-18,-56,0,-31);p.bezierVertex(18,-56,38,-30,30,14);p.endShape();p.fill(colors[1]);p.ellipse(0,-16,25,59);}else if(kind==='lavender'){for(let j=0;j<12;j++){p.noStroke();p.fill(colors[j%3]);p.ellipse(j%2?7:-6,-j*8,13*q,19*q);}}else if(kind==='cherry'){for(let b=-1;b<2;b++){p.push();p.translate(b*18,b?10:0);for(let j=0;j<5;j++)petal(j*72,4,23,10,colors[j%2],q);p.fill('#e6b453');p.circle(0,0,8);p.pop();}}else{let n=kind==='sun'?20:kind==='daisy'?17:kind==='dahlia'?23:kind==='rose'?13:kind==='lotus'?11:kind==='hibiscus'?5:14,L=kind==='rose'||kind==='dahlia'||kind==='lotus'?3:2;for(let z=0;z<L;z++)for(let j=0;j<n-z*5;j++)petal(j*360/(n-z*5)+z*13,z*6,50-z*10,kind==='sun'?8:16-z*2,colors[z%3],q);p.fill(kind==='sun'?'#70442c':kind==='hibiscus'?'#75203d':'#d9aa46');p.noStroke();p.circle(0,0,kind==='sun'?35:20);if(kind==='hibiscus'){p.stroke('#f3c35b');p.strokeWeight(3);p.line(0,0,28,-47);}}p.pop();}
p.draw=()=>{p.clear();t+=.018;if(t>.1){p.noStroke();p.fill('#bf916b');p.ellipse(W/2,H*.91,10,7);}let tops=stems.map((_,i)=>stem(i,at(.5+i*.17,2.4)));tops.forEach((v,i)=>{leaf((W/2+v[0])/2,H*.66-i*8,stems[i][0]>0?30:-30,23,at(2+i*.16,1));leaf(v[0],v[1]+74,stems[i][0]>0?-35:35,18,at(2.5+i*.14,1));bloom(v[0],v[1],i,at(3.4+i*.54,1.6));});if(t>7.3)for(let i=0;i<13;i++){p.fill(255,229,187,65);p.noStroke();p.circle(W/2+Math.cos(i*53+t)*((i%4+2)*24),H*.4+Math.sin(i*53+t)*45,2);}if(!reveal&&t>9.5){reveal=true;setTimeout(()=>$('flower-reveal').classList.add('show'),600);}};});}
// ==================== SISTEMA DE ACCESO ====================
$('access-form').onsubmit=e=>{e.preventDefault();let f=personas.find(p=>p.password.toLowerCase()===$('password').value.trim().toLowerCase());if(!f){$('access-message').textContent='Creo que esa no era... intenta nuevamente.';return;}actual=f;$('access-message').textContent='Acceso concedido.';$('access-message').className='access-message success';setTimeout(()=>{show('garden');$('flower-intro').textContent=f.frase;$('nickname').textContent=f.apodo;ramo(f);},650);};
$('continue-btn').onclick=()=>{show('letter');$('letter-name').textContent=actual.apodo;$('typed-message').textContent='';$('letter-ending').classList.remove('show');let i=0;clearInterval(timer);timer=setInterval(()=>{$('typed-message').textContent+=actual.mensaje[i++]||'';if(i>=actual.mensaje.length){clearInterval(timer);$('cursor').style.display='none';$('letter-ending').classList.add('show');}},20);};$('restart-btn').onclick=()=>{if(sketch)sketch.remove();show('welcome');$('password').value='';$('access-message').textContent='';};
